# development tasks
alias git="hub"
alias g="git"
alias ga="git add"
alias gc='git commit'
alias go="git checkout"
alias gs="git status -sb"
alias gb="git branch"
alias gd="git diff"
alias gdp="git diff --stat | fpp"
alias gp="git up"
alias gpm="git pull origin master"
alias gf="git fetch"
alias grh="git reset head --hard"
alias gg="git push"
alias ggo="git push origin"
alias gr="git remote -v"
alias b='bundle'
alias be='bundle exec'
alias rs='bundle exec rspec'
alias guard='title GUARD ${PWD##*/}; bundle exec guard && wait $!; title Console'
alias evergreen="be rails s -p 4000"
alias dj="be rake jobs:clear jobs:work"
alias sspdf="be fuji_pdf_server start"

# Migration
alias migrate="bundle exec db:migrate"
alias rollback="bundle exec db:rollback"

# Tasks which help fix things
alias reset_db="sh ci/prepare_host_app.sh"
alias panacea="bundle update"

# Fudge
alias fudge="bundle exec fudge build"
alias fudgep="bundle exec fudge build parallel_test"
alias fudgepp="bundle exec fudge build | fpp"

# Directory Nav
alias ..="cd .."
alias ...="cd ../.."
alias dot="cd ~/dotfiles"
alias tools="cd ~/tools"
alias dev="cd ~/development"
alias til="cd ~/til"

# Bash & Vim
alias bashp="vim ~/.bash_profile"
alias basha="vim ~/.bash/bash_aliases"
alias vimrc="vim ~/.vimrc"
alias bash_source="source ~/.bash_profile"

# enable autocomplete support for git aliases
__git_complete g _git_main
__git_complete ga _git_add
__git_complete gc _git_commit
__git_complete go _git_checkout
__git_complete gs _git_status
__git_complete gb _git_branch
__git_complete gd _git_diff
__git_complete gf _git_fetch
__git_complete gg _git_push
__git_complete ggo _git_push

# Open git readme files if they exist in browser
if [ -e README.md ]
  then
    alias readme='open -a "Google Chrome" README.md'
fi

#Open programs
alias chrome='open -a "Google Chrome"'
alias sublime='open -a "Sublime Text 2"'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls -G'
    alias dir='gdir --color=auto'
    alias vdir='gvdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias lla='ls -la'
alias la='ls -A'
alias lr='ls -rtl'
alias l='ls -CF'

# search functions
alias findme='grep -nir --exclude=\*.svn\* --exclude=\*.swp'
alias whouses='grep -lir --exclude=\*.svn\* --exclude=\*.swp'
alias gwologs='grep -ir --exclude=*.log'
alias findfile='find . -iname'
alias inspect='du -csh'
alias fsearch='git ls-files | grep'
